/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R404RouteImport } from './routes/404'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as PHandleRouteImport } from './routes/p.$handle'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminPeopleRouteImport } from './routes/_authenticated/admin/people'
import { Route as AuthenticatedAdminTeamsRouteImport } from './routes/_authenticated/admin/teams'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as AuthenticatedAppLogRouteImport } from './routes/_authenticated/app/log'
import { Route as AuthenticatedAppMapRouteImport } from './routes/_authenticated/app/map'
import { Route as AuthenticatedAppPortfolioRouteImport } from './routes/_authenticated/app/portfolio'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/app/profile'
import { Route as AuthenticatedAppTimelineRouteImport } from './routes/_authenticated/app/timeline'
import { Route as AuthenticatedMentorIndexRouteImport } from './routes/_authenticated/mentor/index'
import { Route as AuthenticatedMentorPairRouteImport } from './routes/_authenticated/mentor/pair'
import { Route as AuthenticatedMentorProfileRouteImport } from './routes/_authenticated/mentor/profile'
import { Route as AuthenticatedMentorTeamsRouteImport } from './routes/_authenticated/mentor/teams'
import { Route as AuthenticatedMentorVerifyRouteImport } from './routes/_authenticated/mentor/verify'
import { Route as AuthenticatedTeamsJoinRouteImport } from './routes/_authenticated/teams/join'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const PHandleRoute = PHandleRouteImport.update({
  id: '/p/$handle',
  path: '/p/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminPeopleRoute =
  AuthenticatedAdminPeopleRouteImport.update({
    id: '/admin/people',
    path: '/admin/people',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTeamsRoute = AuthenticatedAdminTeamsRouteImport.update({
  id: '/admin/teams',
  path: '/admin/teams',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppLogRoute = AuthenticatedAppLogRouteImport.update({
  id: '/app/log',
  path: '/app/log',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppMapRoute = AuthenticatedAppMapRouteImport.update({
  id: '/app/map',
  path: '/app/map',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppPortfolioRoute =
  AuthenticatedAppPortfolioRouteImport.update({
    id: '/app/portfolio',
    path: '/app/portfolio',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppTimelineRoute =
  AuthenticatedAppTimelineRouteImport.update({
    id: '/app/timeline',
    path: '/app/timeline',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMentorIndexRoute =
  AuthenticatedMentorIndexRouteImport.update({
    id: '/mentor/',
    path: '/mentor/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMentorPairRoute = AuthenticatedMentorPairRouteImport.update({
  id: '/mentor/pair',
  path: '/mentor/pair',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMentorProfileRoute =
  AuthenticatedMentorProfileRouteImport.update({
    id: '/mentor/profile',
    path: '/mentor/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMentorTeamsRoute =
  AuthenticatedMentorTeamsRouteImport.update({
    id: '/mentor/teams',
    path: '/mentor/teams',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMentorVerifyRoute =
  AuthenticatedMentorVerifyRouteImport.update({
    id: '/mentor/verify',
    path: '/mentor/verify',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeamsJoinRoute = AuthenticatedTeamsJoinRouteImport.update({
  id: '/teams/join',
  path: '/teams/join',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/auth': typeof AuthRoute
  '/maintenance': typeof MaintenanceRoute
  '/p/$handle': typeof PHandleRoute
  '/admin/people': typeof AuthenticatedAdminPeopleRoute
  '/admin/teams': typeof AuthenticatedAdminTeamsRoute
  '/app/log': typeof AuthenticatedAppLogRoute
  '/app/map': typeof AuthenticatedAppMapRoute
  '/app/portfolio': typeof AuthenticatedAppPortfolioRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/timeline': typeof AuthenticatedAppTimelineRoute
  '/mentor/pair': typeof AuthenticatedMentorPairRoute
  '/mentor/profile': typeof AuthenticatedMentorProfileRoute
  '/mentor/teams': typeof AuthenticatedMentorTeamsRoute
  '/mentor/verify': typeof AuthenticatedMentorVerifyRoute
  '/teams/join': typeof AuthenticatedTeamsJoinRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/mentor/': typeof AuthenticatedMentorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/auth': typeof AuthRoute
  '/maintenance': typeof MaintenanceRoute
  '/p/$handle': typeof PHandleRoute
  '/admin/people': typeof AuthenticatedAdminPeopleRoute
  '/admin/teams': typeof AuthenticatedAdminTeamsRoute
  '/app/log': typeof AuthenticatedAppLogRoute
  '/app/map': typeof AuthenticatedAppMapRoute
  '/app/portfolio': typeof AuthenticatedAppPortfolioRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/timeline': typeof AuthenticatedAppTimelineRoute
  '/mentor/pair': typeof AuthenticatedMentorPairRoute
  '/mentor/profile': typeof AuthenticatedMentorProfileRoute
  '/mentor/teams': typeof AuthenticatedMentorTeamsRoute
  '/mentor/verify': typeof AuthenticatedMentorVerifyRoute
  '/teams/join': typeof AuthenticatedTeamsJoinRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/mentor': typeof AuthenticatedMentorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/404': typeof R404Route
  '/auth': typeof AuthRoute
  '/maintenance': typeof MaintenanceRoute
  '/p/$handle': typeof PHandleRoute
  '/_authenticated/admin/people': typeof AuthenticatedAdminPeopleRoute
  '/_authenticated/admin/teams': typeof AuthenticatedAdminTeamsRoute
  '/_authenticated/app/log': typeof AuthenticatedAppLogRoute
  '/_authenticated/app/map': typeof AuthenticatedAppMapRoute
  '/_authenticated/app/portfolio': typeof AuthenticatedAppPortfolioRoute
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/app/timeline': typeof AuthenticatedAppTimelineRoute
  '/_authenticated/mentor/pair': typeof AuthenticatedMentorPairRoute
  '/_authenticated/mentor/profile': typeof AuthenticatedMentorProfileRoute
  '/_authenticated/mentor/teams': typeof AuthenticatedMentorTeamsRoute
  '/_authenticated/mentor/verify': typeof AuthenticatedMentorVerifyRoute
  '/_authenticated/teams/join': typeof AuthenticatedTeamsJoinRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/mentor/': typeof AuthenticatedMentorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/auth'
    | '/maintenance'
    | '/p/$handle'
    | '/admin/people'
    | '/admin/teams'
    | '/app/log'
    | '/app/map'
    | '/app/portfolio'
    | '/app/profile'
    | '/app/timeline'
    | '/mentor/pair'
    | '/mentor/profile'
    | '/mentor/teams'
    | '/mentor/verify'
    | '/teams/join'
    | '/admin/'
    | '/app/'
    | '/mentor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/auth'
    | '/maintenance'
    | '/p/$handle'
    | '/admin/people'
    | '/admin/teams'
    | '/app/log'
    | '/app/map'
    | '/app/portfolio'
    | '/app/profile'
    | '/app/timeline'
    | '/mentor/pair'
    | '/mentor/profile'
    | '/mentor/teams'
    | '/mentor/verify'
    | '/teams/join'
    | '/admin'
    | '/app'
    | '/mentor'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/404'
    | '/auth'
    | '/maintenance'
    | '/p/$handle'
    | '/_authenticated/admin/people'
    | '/_authenticated/admin/teams'
    | '/_authenticated/app/log'
    | '/_authenticated/app/map'
    | '/_authenticated/app/portfolio'
    | '/_authenticated/app/profile'
    | '/_authenticated/app/timeline'
    | '/_authenticated/mentor/pair'
    | '/_authenticated/mentor/profile'
    | '/_authenticated/mentor/teams'
    | '/_authenticated/mentor/verify'
    | '/_authenticated/teams/join'
    | '/_authenticated/admin/'
    | '/_authenticated/app/'
    | '/_authenticated/mentor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  R404Route: typeof R404Route
  AuthRoute: typeof AuthRoute
  MaintenanceRoute: typeof MaintenanceRoute
  PHandleRoute: typeof PHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$handle': {
      id: '/p/$handle'
      path: '/p/$handle'
      fullPath: '/p/$handle'
      preLoaderRoute: typeof PHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/people': {
      id: '/_authenticated/admin/people'
      path: '/admin/people'
      fullPath: '/admin/people'
      preLoaderRoute: typeof AuthenticatedAdminPeopleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/teams': {
      id: '/_authenticated/admin/teams'
      path: '/admin/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AuthenticatedAdminTeamsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/log': {
      id: '/_authenticated/app/log'
      path: '/app/log'
      fullPath: '/app/log'
      preLoaderRoute: typeof AuthenticatedAppLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/map': {
      id: '/_authenticated/app/map'
      path: '/app/map'
      fullPath: '/app/map'
      preLoaderRoute: typeof AuthenticatedAppMapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/portfolio': {
      id: '/_authenticated/app/portfolio'
      path: '/app/portfolio'
      fullPath: '/app/portfolio'
      preLoaderRoute: typeof AuthenticatedAppPortfolioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/timeline': {
      id: '/_authenticated/app/timeline'
      path: '/app/timeline'
      fullPath: '/app/timeline'
      preLoaderRoute: typeof AuthenticatedAppTimelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mentor/': {
      id: '/_authenticated/mentor/'
      path: '/mentor'
      fullPath: '/mentor/'
      preLoaderRoute: typeof AuthenticatedMentorIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mentor/pair': {
      id: '/_authenticated/mentor/pair'
      path: '/mentor/pair'
      fullPath: '/mentor/pair'
      preLoaderRoute: typeof AuthenticatedMentorPairRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mentor/profile': {
      id: '/_authenticated/mentor/profile'
      path: '/mentor/profile'
      fullPath: '/mentor/profile'
      preLoaderRoute: typeof AuthenticatedMentorProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mentor/teams': {
      id: '/_authenticated/mentor/teams'
      path: '/mentor/teams'
      fullPath: '/mentor/teams'
      preLoaderRoute: typeof AuthenticatedMentorTeamsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mentor/verify': {
      id: '/_authenticated/mentor/verify'
      path: '/mentor/verify'
      fullPath: '/mentor/verify'
      preLoaderRoute: typeof AuthenticatedMentorVerifyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teams/join': {
      id: '/_authenticated/teams/join'
      path: '/teams/join'
      fullPath: '/teams/join'
      preLoaderRoute: typeof AuthenticatedTeamsJoinRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminPeopleRoute: typeof AuthenticatedAdminPeopleRoute
  AuthenticatedAdminTeamsRoute: typeof AuthenticatedAdminTeamsRoute
  AuthenticatedAppLogRoute: typeof AuthenticatedAppLogRoute
  AuthenticatedAppMapRoute: typeof AuthenticatedAppMapRoute
  AuthenticatedAppPortfolioRoute: typeof AuthenticatedAppPortfolioRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppTimelineRoute: typeof AuthenticatedAppTimelineRoute
  AuthenticatedMentorPairRoute: typeof AuthenticatedMentorPairRoute
  AuthenticatedMentorProfileRoute: typeof AuthenticatedMentorProfileRoute
  AuthenticatedMentorTeamsRoute: typeof AuthenticatedMentorTeamsRoute
  AuthenticatedMentorVerifyRoute: typeof AuthenticatedMentorVerifyRoute
  AuthenticatedTeamsJoinRoute: typeof AuthenticatedTeamsJoinRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedMentorIndexRoute: typeof AuthenticatedMentorIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminPeopleRoute: AuthenticatedAdminPeopleRoute,
  AuthenticatedAdminTeamsRoute: AuthenticatedAdminTeamsRoute,
  AuthenticatedAppLogRoute: AuthenticatedAppLogRoute,
  AuthenticatedAppMapRoute: AuthenticatedAppMapRoute,
  AuthenticatedAppPortfolioRoute: AuthenticatedAppPortfolioRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppTimelineRoute: AuthenticatedAppTimelineRoute,
  AuthenticatedMentorPairRoute: AuthenticatedMentorPairRoute,
  AuthenticatedMentorProfileRoute: AuthenticatedMentorProfileRoute,
  AuthenticatedMentorTeamsRoute: AuthenticatedMentorTeamsRoute,
  AuthenticatedMentorVerifyRoute: AuthenticatedMentorVerifyRoute,
  AuthenticatedTeamsJoinRoute: AuthenticatedTeamsJoinRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedMentorIndexRoute: AuthenticatedMentorIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  R404Route: R404Route,
  AuthRoute: AuthRoute,
  MaintenanceRoute: MaintenanceRoute,
  PHandleRoute: PHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
